---

# references
# - https://blog.travis-ci.com/2021-09-03-rust

language: rust
os:
  - linux
  - osx

# Rust 'fuser' crate does not support ARM64, so only test on AMD64.
arch: amd64

jobs:
  include:
    -
      os: linux
      dist: focal
    -
      os: osx
      osx_image: xcode13.1

cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  before_cache: 
    - rm -rf ~/.cargo/registry/index/ # Remove cache files 
    - rm -f  ./target/.rustc_info.json # Remove more cache files that are recursively brought back upon a triggered build
    - find ./target/debug -maxdepth 1 -type f -delete # Delete loose files 
  fast_finish: true
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update              ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo install cargo-lipo ; fi
addons:
  apt:
    packages:
      - libfuse-dev
    update: true
script:
  - cd src
  - cargo build --verbose --workspace
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./build_mac.sh ; fi

  # Uncomment me when tests don't need real CloudWatch logs
  # - cargo test --verbose --workspace