[workspace]

members = [
    "cli",
    "cwl-lib",
    "fuse",
    "regexes",
]

[profile.release]
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
incremental = false
